apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: deepthyck7/myapp:a32b6d9-20251019-0617
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-secret

