---
name: CI - Build and Push Docker Image
permissions:
  contents: write
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Commit ID and Timestamp
        id: vars
        run: |
          echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Set up Docker buildx
        run: docker buildx create --use
      - name: Build and push Docker Image
        run: >
          docker buildx build --platform linux/amd64
          -f docker/dockerfile
          -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${COMMIT_ID}-${BUILD_TIME}
          -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          --push .

          #- name: Push latest tag
          # run: |
          #  docker tag ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${COMMIT_ID}-${BUILD_TIME} \
          #  ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
          # docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

      # Step 7: Update K8s Deployment manifest with new image
      - name: Update deployment manifest with new image
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${COMMIT_ID}-${BUILD_TIME}|" k8s/myapp-deploy.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/myapp-deploy.yaml
          git commit -m "Update image to ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${COMMIT_ID}-${BUILD_TIME}"
          git push
    
      - name: Show final image tag
        run: >
          echo "Pushed image tag:
          ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${COMMIT_ID}-${BUILD_TIME}"
