name: CI/CD to AKS via Docker Hub

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: myapp
  DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/myapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_REPO }}:latest

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/myapp-deployment myapp=${{ env.DOCKER_REPO }}:latest --record || \
        kubectl apply -f k8s-deployment.yaml
        kubectl rollout status deployment/myapp-deployment

